// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH1KH_ntvtM1mzjtmtTUxYDykF73sGQFo',
    appId: '1:1034012339448:web:5ae07821b80178f5eddf0d',
    messagingSenderId: '1034012339448',
    projectId: 'mealtimetable',
    authDomain: 'mealtimetable.firebaseapp.com',
    databaseURL: 'https://mealtimetable-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mealtimetable.appspot.com',
    measurementId: 'G-PZHXBEGZ8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEytldKIZbFjck1Cu98HkZoj7je5pSg-Y',
    appId: '1:1034012339448:android:91221ac0b79c0876eddf0d',
    messagingSenderId: '1034012339448',
    projectId: 'mealtimetable',
    databaseURL: 'https://mealtimetable-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mealtimetable.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-20xDMkkyyDAffD1srq9zaDwJ1xDu3sE',
    appId: '1:1034012339448:ios:c7801b541e4061d6eddf0d',
    messagingSenderId: '1034012339448',
    projectId: 'mealtimetable',
    databaseURL: 'https://mealtimetable-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mealtimetable.appspot.com',
    iosClientId: '1034012339448-s3t6dshpbbqktg6pikgi4vjucqqci3fs.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealtimetable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-20xDMkkyyDAffD1srq9zaDwJ1xDu3sE',
    appId: '1:1034012339448:ios:c7801b541e4061d6eddf0d',
    messagingSenderId: '1034012339448',
    projectId: 'mealtimetable',
    databaseURL: 'https://mealtimetable-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mealtimetable.appspot.com',
    iosClientId: '1034012339448-s3t6dshpbbqktg6pikgi4vjucqqci3fs.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealtimetable',
  );
}
